config/routes.rb
Rails.application.routes.draw do
  resources :artists
  resources :albums
  resources :tracks
  resources :users
  resources :playlists
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :artist
    has_many :tracks
    validates :title, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :albums
    has_many :tracks, through: :albums
    validates :name, presence: true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :users
  has_many :tracks, through: :playlist_tracks
  validates :name, presence: true
end

app/models/track.rb
class Track < ApplicationRecord
    belongs_to :artist
    belongs_to :album
    has_many :playlists, through: :playlist_tracks
    validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :playlists
    validates :username, presence: true, uniqueness: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    def index
        @albums = Album.all
        render json: @albums
    end
    def show
        @album = Album.find(params[:id])
        render json: @album
    end
    def create
        @album = Album.new(album_params)
        if @album.save
            render json: @album, status: :created
        else
            render json: @album.errors, status: :unprocessable_entity
        end
    end
    def destroy
        @album = Album.find(params[:id])
        @album.destroy
        head :no_content
    end
    private
    def album_params
        params.require(:album).permit(:title, :artist_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def index
        @artists = Artist.all
        render json: @artists
    end
    def show
        @artist = Artist.find(params[:id])
        render json: @artist
    end
    def create
        @artist = Artist.new(artist_params)
        if @artist.save
            render json: @artist, status: :created
        else
            render json: @artist.errors, status: :unprocessable_entity
        end
    end
    def destroy
        @artist = Artist.find(params[:id])          
        @artist.destroy
        head :no_content
    end
    private
    def artist_params
        params.require(:artist).permit(:name)
    end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]

  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end

  # GET /playlists/1 or /playlists/1.json
  def show
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: "Playlist was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy!

    respond_to do |format|
      format.html { redirect_to playlists_path, notice: "Playlist was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.expect(playlist: [ :name, :users_id ])
    end
end

app/controllers/spotify_controller.rb
class SpotifyController < ApplicationController
  def index
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def index
        @tracks = Track.all
        render json: @tracks
    end
    def show
        @track = Track.find(params[:id])
        render json: @track
    end
    def create
        @track = Track.new(track_params)
        if @track.save
            render json: @track, status: :created
        else
            render json: @track.errors, status: :unprocessable_entity
        end
    end
    def destroy
        @track = Track.find(params[:id])
        @track.destroy
        head :no_content
    end
    private
    def track_params
        params.require(:track).permit(:title, :artist_id, :album_id, :duration)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        render json: @users
    end
    def show
        @user = User.find(params[:id])
        render json: @user
    end
    def create
        @user = User.new(user_params)
        if @user.save
            render json: @user, status: :created
        else
            render json: @user.errors, status: :unprocessable_entity
        end
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        head :no_content
    end
    private
    def user_params
        params.require(:user).permit(:username, :email)
    end
end

app/helpers/album_helper.rb
module AlbumHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/spotify_helper.rb
module SpotifyHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artist/index.html.erb
<h1>Artist#index</h1>
<p>Find me in app/views/artist/index.html.erb</p>

app/views/playlists/_form.html.erb
<%= form_with(model: playlist) do |form| %>
  <% if playlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :users_id, style: "display: block" %>
    <%= form.text_field :users_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/playlists/_playlist.html.erb
<div id="<%= dom_id playlist %>">
  <p>
    <strong>Name:</strong>
    <%= playlist.name %>
  </p>

  <p>
    <strong>Users:</strong>
    <%= playlist.users_id %>
  </p>

</div>

app/views/playlists/edit.html.erb
<% content_for :title, "Editing playlist" %>

<h1>Editing playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Show this playlist", @playlist %> |
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Playlists" %>

<h1>Playlists</h1>

<div id="playlists">
  <% @playlists.each do |playlist| %>
    <%= render playlist %>
    <p>
      <%= link_to "Show this playlist", playlist %>
    </p>
  <% end %>
</div>

<%= link_to "New playlist", new_playlist_path %>

app/views/playlists/new.html.erb
<% content_for :title, "New playlist" %>

<h1>New playlist</h1>

<%= render "form", playlist: @playlist %>

<br>

<div>
  <%= link_to "Back to playlists", playlists_path %>
</div>

app/views/playlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @playlist %>

<div>
  <%= link_to "Edit this playlist", edit_playlist_path(@playlist) %> |
  <%= link_to "Back to playlists", playlists_path %>

  <%= button_to "Destroy this playlist", @playlist, method: :delete %>
</div>

app/views/spotify/index.html.erb
<h1>Spotify#index</h1>
<p>Find me in app/views/spotify/index.html.erb</p>